@extends('layout')

@section('title', 'Home')

@section('content')

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">MTG Versus</h1>
    <p class="lead">Vote on random card matchups and check out the results!</p>
  </div>
</div>


<div class="container">
	@if(false)
	<div class="row text-center mb-5">
		<div class="col bg-info border border-dark mx-2 rounded">
			<h3 class="mb-0">{{ $votecount }}</h3>
			<small>votes cast</small>
		</div>
		<div class="col">
			
		</div>
		<div class="col">
			
		</div>
	</div>
	@endif
	<h3> What is this? </h3>
	<p>
		This project was created as a follow-up to the Magic Bracket project by David Lyford-Smith. In 2016, David had organized a two-year, 16k+ card, single-elimination bracket tournament to determine the best card printed at that point. You can check out that project at <a href="https://mtgbracket.tumblr.com">Tumblr</a> or its associated <a href="https://www.reddit.com/r/mtgbracket/">subreddit</a>.
	</p>
	<p>
		Back during that project, I had created a <a href="https://cs.mcgill.ca/~imilos2/MTGB">website</a> for tracking the results of all the votes and the path that any card took in the tournament. I've always wanted to do something once the project finished, and I thought of this project - have random 1v1 matchups be generated for easy voting on-the-fly. The idea was born out of the combination of the burnout and the excitement generated by the Magic Bracket. 
	</p>
	<h3> What's next? </h3>
	<p>
		If this picks up enough steam, my current plans include:
		<ul>
			<li>Add a stat tracker above for number of votes, number of users, maybe most successful card?</li>
			<li>Add a filtering option for a less random pick. This would still be limited so that no one super-votes one card over and over and over.</li>
			<li>Add an actual authentication system (currently, the username is just the password itself in a sense).</li>
			<li>Add a "review" section to each card, similar to the Gatherer, but with Lyford-Smith's 4 categories (Art, Flavor, Design, Power Level). Each user can then leave a review for any cards they want, and the summary of the reviews could be displayed below any voting. Need the authentication system for this so we can guarantee no one changes your reviews of cards.</li>
		</ul>

		And as a longer-term idea, especially if there are requests for it, I could try to implement a tournament system, so people can create their own tournaments and hold them. 

		In the meantime, you can message me on the <b><a href="https://www.reddit.com/r/mtgbracket/comments/hhrb1y/mtg_versus/?">Reddit thread</a></b> for any suggestions.
	</p>
</div>

@endsection